/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hazem_apps_libcurltest_Libcurl */

#ifndef _Included_com_hazem_apps_libcurltest_Libcurl
#define _Included_com_hazem_apps_libcurltest_Libcurl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hazem_apps_libcurltest_Libcurl
 * Method:    requestPage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hazem_apps_libcurltest_Libcurl_requestPage
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
